//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_1_DB_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string ADDRESS_VALUE { get; set; }
    
        public virtual User User { get; set; }
    }
}
