//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Source_Control_Final_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public Nullable<double> emp_salary { get; set; }
        public string emp_address { get; set; }
        public string emp_designation { get; set; }
        public string emp_dept { get; set; }
    }
}
