//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_List
    {
        public int Product_id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public int Quantity { get; set; }
        public string Short_Description { get; set; }
        public string Long_Description { get; set; }
        public byte[] Small_Image { get; set; }
        public double Price { get; set; }
    }
}
